### ISSUE TITLE
Remove check for citation or thesis cmodel, and avoid "trying to get property of non object" errors

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/islandora_badges#1]
By checking that the XPath that checks for the presence of a DOI contains at least one DOI, we can prevent "trying to get property of non object" errors when no DOI is present. This check will also prevent the errors when a thesis or citation doesn't have a DOI.

I'll open a pull request to add this check.

**Comment by bondjimbond** [comment]
Merged it - but it seems to still be generating errors (see comments on your pull request).

**Comment by mjordan** [comment]
https://github.com/bondjimbond/islandora_badges/blob/7.x/islandora_badges.module#L56 is asking for the MODS datastream. Can you confirm that the collections where this error is occurring don't have MODS datastreams? If they don't (which is what I'm guessing), we need to add logic to check for the existence of MODS.

The code itself could be pretty simple, e.g.

``` php
if (!isset($object['MODS'])) {
  return;
}
```

This would go just before line 55 and again just before  line 88. In fact we might want to load the MODS datastream and do the Xpath query before the block-specific case statements (maybe just after line 49) since it applies to both cases.

**Comment by mjordan** [comment]
The code itself could be pretty simple, e.g.

```php
if (!isset($object['MODS'])) {
  return;
}
```
just before line 55 and again just before line 88. In fact, we may also want to do the loading of the MODS datastream and the XPath stuff prior to the case statement since it applies to both.

**Comment by bondjimbond** [comment]
I believe you're right. It looks like all the Collection objects (in Vagrant by default, I think) don't have MODS datastreams. I tried ingesting a basic image with a barebones MODS file, and no problems.

Can you add the relevant logic and submit a pull request?

**Comment by mjordan** [comment]
OK, PR created. I just added the check for the presence of the MODS datastream, I didn't relocate the code that gets the DOI outside of the case statement.

Tested with collection objects that lack a MODS datastream.

**Comment by mjordan** [comment]
Can I close this issue?
