### ISSUE TITLE
Split into sub-modules

### ISSUE THREAD

**Issue by whikloj** [bondjimbond/islandora_badges#17]
@bondjimbond 
I did this, but I don't use scholar nor badges so I need some help with testing.

My branch is here https://github.com/whikloj/islandora_badges/tree/7.x-merged

I'll keep working and then submit a PR to your repo.

**Comment by mjordan** [comment]
@whikloj should all the submodules be in a `modules` directory, like

```
modules/
 	islandora_altmetrics
	islandora_scopus
	islandora_wos
```

**Comment by whikloj** [comment]
@mjordan its not required, but I can do that if you'd like.

**Comment by mjordan** [comment]
Whatever the most common convention is. Does make for a cleaner directory structure but as you say, it's not technically required.

**Comment by whikloj** [comment]
Done and here is a PR. I can make changes as you desire.
https://github.com/bondjimbond/islandora_badges/pull/18

**Comment by whikloj** [comment]
I should also mention that I wasn't clear why these badges required the ir:citationModel content model.

I left that restriction in place for the altmetrics, but I did not extend it to the Scopus or Web of Science badges.

https://github.com/whikloj/islandora_badges/blob/7.x-merged/modules/islandora_altmetrics/islandora_altmetrics.module#L47

We could make this the same across all three, make it the same and configurable, or leave it up to the individual badges.

**Comment by bondjimbond** [comment]
Restriction was set in the original Altmetrics module. I don't know why either... probably just because that's what the original creators were interested in.

I'm always a fan of making things configurable.

I'll test your PR today.

**Comment by bondjimbond** [comment]
Looking back, I believe I ended up not deleting the requirement because of the error message that comes up when viewing Collection objects.
