### ISSUE TITLE
Configure which Content-Models to display badges on.

### ISSUE THREAD

**Issue by whikloj** [bondjimbond/islandora_badges#19]
Currently altmetrics only displays badges for ir:citationModels.

We could allow people to select which Content-models to display badges on.

**Comment by bondjimbond** [comment]
Agreed. I'm not sure why the Altmetric module made that restriction originally; suspect it was because the creator was just interest in citations. I see no reason it's needed.

Once the split-into-submodules thing is done, I'll test out a branch cutting this requirement.

**Comment by whikloj** [comment]
I have a branch with some work ready, it is based off the sub-module branch so I won't open a PR until we get that working.

It allows you to select from a list of all available content-models and uses that list to determine whether to show badges. Currently it is designed as a single list for all badges, but you could extend it to allow separate lists for each sub-module.

I only changed Altmetrics as it was the only one with this restriction by default. But it would be easy to add to the rest.

But you can see and try it here.
https://github.com/whikloj/islandora_badges/tree/issue-19
