### ISSUE TITLE
Remove Scopus badge when data "unavailable"

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_badges#5]
An "unavailable" badge appears when Scopus citation data is not available for an object that has a DOI but no citation data available in Scopus.

Example: http://arcabc.ca/islandora/object/unbc%3A59

Is there any way to identify an Unavailable result and exclude it from display?

**Comment by mjordan** [comment]
We'd need to do some testing to see what Scopus's response is when this happens, but if it's something that we can detect, we can use it. I can take a look if you want.

**Comment by mjordan** [comment]
Here is the HTML returned from the Scopus API using a DOI known to return some results (API key in the returned HTML XXXed out):

``` html
<a target="_blank" href="http://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&amp;scp=84926115490&amp;origin=inward"><image src="http://api.elsevier.com/content/abstract/citation-count?eid=2-s2.0-84926115490&amp;httpAccept=image%2Fjpeg&amp;apiKey=XXX" border="0" alt="cited by count"/></a>
```

And the HTML returned using the DOI you mention above, for which there are no results in Scopus:

``` html
<a target="_blank" href="http://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&amp;scp=&amp;origin=inward"><image href="http://api.elsevier.com/content/abstract/citation-count?doi=&amp;httpAccept=image%2Fjpeg" border="0" alt="unavailable"/></a>
```

The "Abstract Citation Count API", which I believe is the one we're using, is documented at http://dev.elsevier.com/sc_apis.html as only returning text/html, so it looks like our best bet is to rely on the value of the `<img>` tag's `alt` attribute to tell us whether the data is available or not. In the successful example above, we have `alt="cited by count"` and in the unsuccessful one, we have `alt="unavailable"`. Easy enough to check for.

Next question is, what should we display to the user when there the citation count is unavailable? No block, or the a block containing a message indicating that nothing was found?

While we're evaluating the HTML that we get back from Scopus, we probably should also test to make sure that the HTTP response code is 200, which is what both the successful and unsuccessful calls return. If we get a non-200 HTTP response code we should display a sensible error message to the user (or perhaps no block).

**Comment by bondjimbond** [comment]
Great stuff -- thanks for investigating, Mark.

I think I prefer to display no badge when there are no results, as the Altmetric one does, to keep things clean. Although I suppose this could be a configurable thing? i.e. a checkbox on the admin form whether to report "no results in Scopus" when no citations exist in Scopus? (The more configuration the better, in my opinion - though that may eventually require me to reorganize the form.)

When there's a weird response, yes, I think no block is probably preferred for the general public. If possible, an administrator should be able to see an error, but definitely not the user. (I guess this would have to be a permission thing -- a good opportunity for me to learn how to set up permission handling?)

**Comment by mjordan** [comment]
:+1: to the idea of showing the error for admin users and nothing for other users.

**Comment by bondjimbond** [comment]
And for the general public, I like no block by default for anything other than a positive result, for this and future blocks - but allow admins the option to show something else. Preference I think among repository admins is to only show the good stuff.
