### ISSUE TITLE
Add Web of Science badge

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_badges#6]
Use the AMR (Article Match Retrieval) API to retrieve the following data from Web of Science:
- Citation count ("times cited")
- Citing Article URL
  Examples: http://wokinfo.com/directlinks/amrfaq/

http://ipscience-help.thomsonreuters.com/LAMRService/WebServicesOverviewGroup/dataAcceptedByLAMR/guidelinesSpecifyingCitationsWoSCCC.html

Find more documentation on how to make an AMR request too.

**Comment by bondjimbond** [comment]
Does this make any sense at all?

http://ipscience-help.thomsonreuters.com/LAMRService/WebServiceOperationsGroup/requestAPIDCI.html

**Comment by mjordan** [comment]
Not out of context, but looking at http://ipscience-help.thomsonreuters.com/LAMRService/WebServicesOverviewGroup/overview.html I assume that the XML you link to needs to be POSTed to an API endpoint that you need to contact ThomsonReuters to get access to. After the XML request has been sent to the API, it would return a response containing http://ipscience-help.thomsonreuters.com/LAMRService/WebServiceOperationsGroup/responseAPIDCI.html. Their documentation isn't clear but that's what it looks like to me.

**Comment by bondjimbond** [comment]
You may be right. Finding out whether the URL they give in the XML is the correct API endpoint or not is part of the trouble. The rest of the trouble is figuring out how exactly to post XML to an endpoint in PHP -- which I think I can figure out eventually, but I have to know that my endpoint is correct first. 

They said that I should have my credentials by the end of the week, so we'll find out then.

**Comment by mjordan** [comment]
https://api.drupal.org/api/drupal/includes!common.inc/function/drupal_http_request/7.x with a "method" option of POST will work. We can work on this together if you want.

**Comment by bondjimbond** [comment]
Great! Thanks. That seems like it should be a lot simpler than the options I've been looking at, but I'd much appreciate the help understanding it.

**Comment by bondjimbond** [comment]
Did it! Merged webofscience branch and deleted.
