### ISSUE TITLE
Put badge-specific code in separate functions

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/islandora_badges#9]
Thought I'd open this issue so we don't forget about it. Low priority for now?

The badge-specific code inside the `case` blocks in `islandora_badges_block_view()` should be refactored into functions, which in turn, could be placed in an include file. This would make adding new badges easier, plus keep the .module file smaller and more maintainable.

**Comment by bondjimbond** [comment]
Thanks - good to have it there to keep track. Agreed that it's low priority for now. I'll focus on getting WoS working, and then address this issue.

**Comment by bondjimbond** [comment]
Covered by #17
